//------------------------------------------------------------------------------
// Copyright (c) 2005, 2006 IBM Corporation and others.
// All rights reserved. This program and the accompanying materials
// are made available under the terms of the Eclipse Public License v1.0
// which accompanies this distribution, and is available at
// http://www.eclipse.org/legal/epl-v10.html
// 
// Contributors:
// IBM Corporation - initial implementation
//------------------------------------------------------------------------------

// This file will include dynamically generated process layout related data from 
// the publishing service 
contentPage.processPage.imageFiles["_SuWj4dOPEdyqlogshP8l4g,_nfpBkVQwEd2i9JHp7xurvw,_6togYdOPEdyqlogshP8l4gActivity"]="./../../process.openup.base/deliveryprocesses/resources/construction_phase_iteration_5BD4A7D6_fdf0b00_Activity.jpeg"
contentPage.processPage.imageFiles["_SuWj4dOPEdyqlogshP8l4g,_8tQrUVQvEd2i9JHp7xurvwActivity"]="./../../process.openup.base/deliveryprocesses/resources/Inception Phase_5229EC90_ba040c1e_Activity.jpeg"
contentPage.processPage.imageFiles["_SuWj4dOPEdyqlogshP8l4g,_nfpBkVQwEd2i9JHp7xurvw,_6togYdOPEdyqlogshP8l4g,_CqFrgdOOEdyqlogshP8l4gActivity"]="./../../process.openup.base/capabilitypatterns/resources/develop_solution_2E5A12EB_b4ccac3f_Activity.jpeg"
contentPage.processPage.imageFiles["_SuWj4dOPEdyqlogshP8l4g,_pOgXIVQwEd2i9JHp7xurvw,_7bg6EdOPEdyqlogshP8l4g,_-iix4dOOEdyqlogshP8l4gActivity"]="./../../process.openup.base/capabilitypatterns/resources/develop_solution_8E22EA8F_6dcd4be3_Activity.jpeg"
contentPage.processPage.imageFiles["_SuWj4dOPEdyqlogshP8l4g,_ieYHIVQwEd2i9JHp7xurvw,_51ewYdOPEdyqlogshP8l4gActivity"]="./../../process.openup.base/deliveryprocesses/resources/elaboration_phase_iteration_579A68CE_b288583b_Activity.jpeg"
contentPage.processPage.imageFiles["_SuWj4dOPEdyqlogshP8l4g,_ieYHIVQwEd2i9JHp7xurvwActivity"]="./../../process.openup.base/deliveryprocesses/resources/Elaboration Phase_F6EBBC8B_5ec5dc19_Activity.jpeg"
contentPage.processPage.imageFiles["_SuWj4dOPEdyqlogshP8l4g,_pOgXIVQwEd2i9JHp7xurvw,_7bg6EdOPEdyqlogshP8l4gActivity"]="./../../process.openup.base/deliveryprocesses/resources/transition_phase_iteration_9880C0E_29eed300_Activity.jpeg"
contentPage.processPage.imageFiles["_SuWj4dOPEdyqlogshP8l4g,_ieYHIVQwEd2i9JHp7xurvw,_51ewYdOPEdyqlogshP8l4g,_aSrtcdOOEdyqlogshP8l4g,_TV_k8dOKEdyqlogshP8l4gActivity"]="./../../process.openup.base/capabilitypatterns/resources/develop_solution_4A08A92A_62694d6_Activity.jpeg"
contentPage.processPage.imageFiles["_SuWj4dOPEdyqlogshP8l4g,_8tQrUVQvEd2i9JHp7xurvw,_kYVSUdOPEdyqlogshP8l4gActivity"]="./../../process.openup.base/deliveryprocesses/resources/inception_phase_iteration_1EFD4B4F_1e8aebc1_Activity.jpeg"
contentPage.processPage.imageFiles["_SuWj4dOPEdyqlogshP8l4gActivity"]="./../../process.openup.base/deliveryprocesses/resources/openup_lifecycle_EE511F3A_ee511f3a_Activity.jpeg"
contentPage.processPage.imageFiles["_SuWj4dOPEdyqlogshP8l4g,_ieYHIVQwEd2i9JHp7xurvw,_51ewYdOPEdyqlogshP8l4g,_eyv_UdOOEdyqlogshP8l4gActivity"]="./../../process.openup.base/capabilitypatterns/resources/develop_solution_C9559260_c5bc37ef_Activity.jpeg"
contentPage.processPage.imageFiles["_SuWj4dOPEdyqlogshP8l4g,_nfpBkVQwEd2i9JHp7xurvwActivity"]="./../../process.openup.base/deliveryprocesses/resources/Construction Phase_BD0D5748_24e776d6_Activity.jpeg"
contentPage.processPage.imageFiles["_SuWj4dOPEdyqlogshP8l4g,_pOgXIVQwEd2i9JHp7xurvwActivity"]="./../../process.openup.base/deliveryprocesses/resources/Transition Phase_14EE9310_7cc8b29e_Activity.jpeg"
contentPage.processPage.imageFiles["_SKnA1uL9EdyM47cGD2jiaQActivity"]="./../../practice.mgmt.risk_value_lifecycle.base/capabilitypatterns/resources/risk_value_lifecycle_phases_4D57D552_4d57d552_Activity.jpeg"
contentPage.processPage.imageFiles["_h0Gs8dONEdyqlogshP8l4gActivity"]="./../../process.openup.base/capabilitypatterns/resources/inception_phase_iteration_B1800053_b1800053_Activity.jpeg"
contentPage.processPage.imageFiles["_aUsVEdONEdyqlogshP8l4g,_aSrtcdOOEdyqlogshP8l4g,_TV_k8dOKEdyqlogshP8l4gActivity"]="./../../process.openup.base/capabilitypatterns/resources/develop_solution_4A08A92A_92220b44_Activity.jpeg"
contentPage.processPage.imageFiles["_aUsVEdONEdyqlogshP8l4g,_eyv_UdOOEdyqlogshP8l4gActivity"]="./../../process.openup.base/capabilitypatterns/resources/develop_solution_C9559260_5616985d_Activity.jpeg"
contentPage.processPage.imageFiles["_aUsVEdONEdyqlogshP8l4gActivity"]="./../../process.openup.base/capabilitypatterns/resources/elaboration_phase_iteration_54DFA2A9_54dfa2a9_Activity.jpeg"
contentPage.processPage.imageFiles["_RQi0AdONEdyqlogshP8l4g,_CqFrgdOOEdyqlogshP8l4gActivity"]="./../../process.openup.base/capabilitypatterns/resources/develop_solution_2E5A12EB_b00f5fbb_Activity.jpeg"
contentPage.processPage.imageFiles["_RQi0AdONEdyqlogshP8l4gActivity"]="./../../process.openup.base/capabilitypatterns/resources/construction_phase_iteration_9AC1727C_9ac1727c_Activity.jpeg"
contentPage.processPage.imageFiles["_pzQU0dONEdyqlogshP8l4g,_-iix4dOOEdyqlogshP8l4gActivity"]="./../../process.openup.base/capabilitypatterns/resources/develop_solution_8E22EA8F_ee2c9098_Activity.jpeg"
contentPage.processPage.imageFiles["_pzQU0dONEdyqlogshP8l4gActivity"]="./../../process.openup.base/capabilitypatterns/resources/transition_phase_iteration_57B0A6B5_57b0a6b5_Activity.jpeg"
contentPage.processPage.imageFiles["_KaeNsdOFEdyqlogshP8l4g,_TV_k8dOKEdyqlogshP8l4gActivity"]="./../../process.openup.base/capabilitypatterns/resources/develop_solution_4A08A92A_5f3b39d9_Activity.jpeg"
contentPage.processPage.imageFiles["_RXGoodOFEdyqlogshP8l4gActivity"]="./../../process.openup.base/capabilitypatterns/resources/develop_solution_4FBB0E6E_4fbb0e6e_Activity.jpeg"
contentPage.processPage.elementUrls["_4ypNIO-YEdyEMtC_IfEALw"] = ["Project Plan","process.openup.base/capabilitypatterns/project_plan_73DF1826.html"];
contentPage.processPage.elementUrls["_N0aPgUVEEeK93ZZqiMLBsA"] = ["Use-Case Model","process.openup.base/capabilitypatterns/use_case_model_8D1A8AA1.html"];
contentPage.processPage.elementUrls["_HGqkMdnTEdyNj6EOmqy5Rg"] = ["Work Items List","process.openup.base/capabilitypatterns/work_items_list_A8A07014.html"];
contentPage.processPage.elementUrls["_SKnAyOL9EdyM47cGD2jiaQ"] = ["Construction Iteration [1..n]","practice.mgmt.risk_value_lifecycle.base/capabilitypatterns/construction_iteration_9D2879E4.html"];
contentPage.processPage.elementUrls["_EOwqptOLEdyqlogshP8l4g"] = ["System-Wide Requirements","process.openup.base/capabilitypatterns/system_wide_requirements_FD9127D9.html"];
contentPage.processPage.elementUrls["_BWf5gtOKEdyqlogshP8l4g"] = ["Architecture Notebook","process.openup.base/capabilitypatterns/architecture_notebook_F61D2121.html"];
contentPage.processPage.elementUrls["_ofI9sJlWEeGlkdGl1HQlDA"] = ["Develop Training Materials","process.openup.base/capabilitypatterns/develop_training_materials_761EBEBA.html"];
contentPage.processPage.elementUrls["_N8RLAUVEEeK93ZZqiMLBsA"] = ["Vision","process.openup.base/capabilitypatterns/vision_FB158F7A.html"];
contentPage.processPage.elementUrls["_N90qMUVEEeK93ZZqiMLBsA"] = ["Developer","process.openup.base/capabilitypatterns/developer_34A6C6B6.html"];
contentPage.processPage.elementUrls["_y7a0IpiLEeGOvpP1fVrVNA"] = ["Infrastructure","process.openup.base/capabilitypatterns/infrastructure_812ADD40.html"];
contentPage.processPage.elementUrls["_3MJwNJoQEeGnJt_Qpwdfdg"] = ["Project Defined Process","process.openup.base/capabilitypatterns/project_defined_process_12C4DE93.html"];
contentPage.processPage.elementUrls["_aSrtcdOOEdyqlogshP8l4g"] = ["Develop the Architecture","process.openup.base/capabilitypatterns/develop_architecture_D0F73FC9.html"];
contentPage.processPage.elementUrls["_N9zcEUVEEeK93ZZqiMLBsA"] = ["Technical Writer","process.openup.base/capabilitypatterns/technical_writer_C58E54A6.html"];
contentPage.processPage.elementUrls["_frh-QtOKEdyqlogshP8l4g"] = ["Design","process.openup.base/capabilitypatterns/design_B2747424.html"];
contentPage.processPage.elementUrls["_y1MMMdOJEdyqlogshP8l4g"] = ["Risk List","process.openup.base/capabilitypatterns/risk_list_4C04C17E.html"];
contentPage.processPage.elementUrls["_N24UsUVEEeK93ZZqiMLBsA"] = ["Implementation","process.openup.base/capabilitypatterns/implementation_2A044929.html"];
contentPage.processPage.elementUrls["_N5hZAUVEEeK93ZZqiMLBsA"] = ["Stakeholder","process.openup.base/capabilitypatterns/stakeholder_FC8473AF.html"];
contentPage.processPage.elementUrls["_N-3MAUVEEeK93ZZqiMLBsA"] = ["Design","process.openup.base/capabilitypatterns/design_31946F2F.html"];
contentPage.processPage.elementUrls["_sL8xMZlXEeGlkdGl1HQlDA"] = ["Deploy Release to Production","process.openup.base/capabilitypatterns/deploy_release_to_production_BAAD4603.html"];
contentPage.processPage.elementUrls["_7bg6EdOPEdyqlogshP8l4g"] = ["Transition Iteration [1..n]","process.openup.base/deliveryprocesses/transition_phase_iteration_9880C0E.html"];
contentPage.processPage.elementUrls["_N-TLUUVEEeK93ZZqiMLBsA"] = ["Course Developer","process.openup.base/capabilitypatterns/course_developer_9B2C5A19.html"];
contentPage.processPage.elementUrls["_ePfxAFTiEd2ZeY-22kx0mw"] = ["Initial Operational Capability Milestone","practice.mgmt.risk_value_lifecycle.base/capabilitypatterns/Initial Operational Capability_D87619F1.html"];
contentPage.processPage.elementUrls["_tzWYwNnFEdyNWvE4rz3mXQ"] = ["[Technical Specification]","process.openup.base/capabilitypatterns/technical_specification_slot_194926F3.html"];
contentPage.processPage.elementUrls["_oZgCsdOEEdyqlogshP8l4g"] = ["Plan and Manage Iteration","process.openup.base/capabilitypatterns/plan_manage_iteration_F9713A62.html"];
contentPage.processPage.elementUrls["_buG4sdOFEdyqlogshP8l4g"] = ["Test Solution","process.openup.base/capabilitypatterns/test_solution_D16D88FC.html"];
contentPage.processPage.elementUrls["_N2c24UVEEeK93ZZqiMLBsA"] = ["Test Log","process.openup.base/capabilitypatterns/test_log_3288A196.html"];
contentPage.processPage.elementUrls["_y7az-5iLEeGOvpP1fVrVNA"] = ["Develop Backout Plan","process.openup.base/capabilitypatterns/develop_backout_plan_DD50396B.html"];
contentPage.processPage.elementUrls["_AZ58IdOPEdyqlogshP8l4g"] = ["Test Solution","process.openup.base/capabilitypatterns/test_solution_55FA17AC.html"];
contentPage.processPage.elementUrls["_N6BvUUVEEeK93ZZqiMLBsA"] = ["System-Wide Requirements","process.openup.base/capabilitypatterns/system_wide_requirements_811FF29E.html"];
contentPage.processPage.elementUrls["_3MJwMJoQEeGnJt_Qpwdfdg"] = ["Deploy the Process","process.openup.base/capabilitypatterns/deploy_process_4E32FC74.html"];
contentPage.processPage.elementUrls["_Nyye4UVEEeK93ZZqiMLBsA"] = ["Build","process.openup.base/capabilitypatterns/build_91CE9DFA.html"];
contentPage.processPage.elementUrls["_N0IisUVEEeK93ZZqiMLBsA"] = ["Project Plan","process.openup.base/capabilitypatterns/project_plan_22689706.html"];
contentPage.processPage.elementUrls["_y7a0K5iLEeGOvpP1fVrVNA"] = ["User Documentation","process.openup.base/capabilitypatterns/user_documentation_73287743.html"];
contentPage.processPage.elementUrls["_6R37Md_1EdyOsumnGvWsEg"] = ["[Technical Design]","process.openup.base/capabilitypatterns/technical_design_slot_68337E8D.html"];
contentPage.processPage.elementUrls["_DZttwJlXEeGlkdGl1HQlDA"] = ["Plan Deployment","process.openup.base/capabilitypatterns/plan_deployment_1136026.html"];
contentPage.processPage.elementUrls["_frh-QdOKEdyqlogshP8l4g"] = ["[Technical Specification]","process.openup.base/capabilitypatterns/technical_specification_slot_A7D69414.html"];
contentPage.processPage.elementUrls["_N2UUAUVEEeK93ZZqiMLBsA"] = ["Developer","process.openup.base/capabilitypatterns/developer_A162C15A.html"];
contentPage.processPage.elementUrls["_y1MMM9OJEdyqlogshP8l4g"] = ["[Technical Architecture]","process.openup.base/capabilitypatterns/technical_architecture_slot_BF7C7753.html"];
contentPage.processPage.elementUrls["_g8cPsdOOEdyqlogshP8l4g"] = ["Ongoing Tasks","process.openup.base/capabilitypatterns/ongoing_tasks_6EA48E23.html"];
contentPage.processPage.elementUrls["_HDOWUdOLEdyqlogshP8l4g"] = ["[Technical Specification]","process.openup.base/capabilitypatterns/technical_specification_slot_2BF7A564.html"];
contentPage.processPage.elementUrls["_y7a0JZiLEeGOvpP1fVrVNA"] = ["Deliver Release Communications","process.openup.base/capabilitypatterns/deliver_release_communications_5723AB49.html"];
contentPage.processPage.elementUrls["_N5I-gUVEEeK93ZZqiMLBsA"] = ["Release","process.openup.base/capabilitypatterns/release_F69FDFDB.html"];
contentPage.processPage.elementUrls["_FJm0fpoPEeGnJt_Qpwdfdg"] = ["Implementation","process.openup.base/capabilitypatterns/implementation_96CEC720.html"];
contentPage.processPage.elementUrls["_N3-g4UVEEeK93ZZqiMLBsA"] = ["Use-Case Model","process.openup.base/capabilitypatterns/use_case_model_F7449C02.html"];
contentPage.processPage.elementUrls["_DaTjpZlXEeGlkdGl1HQlDA"] = ["Release Communications","process.openup.base/capabilitypatterns/release_communications_7002A7A.html"];
contentPage.processPage.elementUrls["_N7d5wUVEEeK93ZZqiMLBsA"] = ["Developer Test","process.openup.base/capabilitypatterns/developer_test_345496DA.html"];
contentPage.processPage.elementUrls["_N2ViIUVEEeK93ZZqiMLBsA"] = ["Stakeholder","process.openup.base/capabilitypatterns/stakeholder_BEE34BC5.html"];
contentPage.processPage.elementUrls["_N4eQIUVEEeK93ZZqiMLBsA"] = ["Design","process.openup.base/capabilitypatterns/design_22979C40.html"];
contentPage.processPage.elementUrls["_TUrpQFTiEd2ZeY-22kx0mw"] = ["Lifecycle Objectives Milestone","practice.mgmt.risk_value_lifecycle.base/capabilitypatterns/Lifecycle Objectives Milestone_DFF2A143.html"];
contentPage.processPage.elementUrls["_N39SwUVEEeK93ZZqiMLBsA"] = ["Vision","process.openup.base/capabilitypatterns/vision_33B9337F.html"];
contentPage.processPage.elementUrls["_y7a0HZiLEeGOvpP1fVrVNA"] = ["Execute Backout Plan (if necessary)","process.openup.base/capabilitypatterns/execute_backout_plan_CDFFE70B.html"];
contentPage.processPage.elementUrls["_NzqBkUVEEeK93ZZqiMLBsA"] = ["Project Manager","process.openup.base/capabilitypatterns/project_manager_7E6517C9.html"];
contentPage.processPage.elementUrls["_N5KzsUVEEeK93ZZqiMLBsA"] = ["Release Communications","process.openup.base/capabilitypatterns/release_communications_D8F98D1A.html"];
contentPage.processPage.elementUrls["_NyjOUUVEEeK93ZZqiMLBsA"] = ["Test Log","process.openup.base/capabilitypatterns/test_log_A97CCDD2.html"];
contentPage.processPage.elementUrls["_y7a0LJiLEeGOvpP1fVrVNA"] = ["Develop Product Documentation and Training","process.openup.base/capabilitypatterns/prep_doc_trng_D5A98F77.html"];
contentPage.processPage.elementUrls["_N33MIUVEEeK93ZZqiMLBsA"] = ["Developer","process.openup.base/capabilitypatterns/developer_A1B9412D.html"];
contentPage.processPage.elementUrls["_51ewYdOPEdyqlogshP8l4g"] = ["Elaboration Iteration [1..n]","process.openup.base/deliveryprocesses/elaboration_phase_iteration_579A68CE.html"];
contentPage.processPage.elementUrls["_eWxZgdOEEdyqlogshP8l4g"] = ["Initiate Project","process.openup.base/capabilitypatterns/initiate_project_37A47ADB.html"];
contentPage.processPage.elementUrls["_6togYdOPEdyqlogshP8l4g"] = ["Construction Iteration [1..n]","process.openup.base/deliveryprocesses/construction_phase_iteration_5BD4A7D6.html"];
contentPage.processPage.elementUrls["_y7a0B5iLEeGOvpP1fVrVNA"] = ["Prepare for Release","process.openup.base/capabilitypatterns/prepare_for_release_8A07842C.html"];
contentPage.processPage.elementUrls["_N_I40UVEEeK93ZZqiMLBsA"] = ["Release","process.openup.base/capabilitypatterns/release_6C093EA3.html"];
contentPage.processPage.elementUrls["_N3950UVEEeK93ZZqiMLBsA"] = ["System-Wide Requirements","process.openup.base/capabilitypatterns/system_wide_requirements_954C0848.html"];
contentPage.processPage.elementUrls["_y7a0AZiLEeGOvpP1fVrVNA"] = ["Release Controls","process.openup.base/capabilitypatterns/release_controls_6E02B832.html"];
contentPage.processPage.elementUrls["_F68foNOLEdyqlogshP8l4g"] = ["Detail System-Wide Requirements","process.openup.base/capabilitypatterns/detail_system_wide_requirements_B4381DEE.html"];
contentPage.processPage.elementUrls["_N0-3QUVEEeK93ZZqiMLBsA"] = ["Tool Specialist","process.openup.base/capabilitypatterns/tool_specialist_4F647DCE.html"];
contentPage.processPage.elementUrls["_uxDPEdOOEdyqlogshP8l4g"] = ["Plan and Manage Iteration","process.openup.base/capabilitypatterns/plan_manage_iteration_91628C02.html"];
contentPage.processPage.elementUrls["_gX7xQNOKEdyqlogshP8l4g"] = ["[Technical Implementation]","process.openup.base/capabilitypatterns/technical_implementation_slot_E32AE6DF.html"];
contentPage.processPage.elementUrls["_-AGJcO-YEdyEMtC_IfEALw"] = ["[Project Definition and Scope]","process.openup.base/capabilitypatterns/project_definition_and_scope_slot_ABFD6480.html"];
contentPage.processPage.elementUrls["_N8iQwUVEEeK93ZZqiMLBsA"] = ["Developer Test","process.openup.base/capabilitypatterns/developer_test_45B96D52.html"];
contentPage.processPage.elementUrls["_N7QeYUVEEeK93ZZqiMLBsA"] = ["Project Manager","process.openup.base/capabilitypatterns/project_manager_8A2B825B.html"];
contentPage.processPage.elementUrls["_y7kklJiLEeGOvpP1fVrVNA"] = ["Develop Product Documentation","process.openup.base/capabilitypatterns/develop_product_documentation_DA7CBA88.html"];
contentPage.processPage.elementUrls["_frOcQNOKEdyqlogshP8l4g"] = ["Design the Solution","process.openup.base/capabilitypatterns/design_solution_7C602F6D.html"];
contentPage.processPage.elementUrls["_NzxWUUVEEeK93ZZqiMLBsA"] = ["Tester","process.openup.base/capabilitypatterns/tester_CE428A8D.html"];
contentPage.processPage.elementUrls["_tcRJkZlXEeGlkdGl1HQlDA"] = ["Provide Product Training","process.openup.base/capabilitypatterns/provide_product_training_FDDBC3D3.html"];
contentPage.processPage.elementUrls["_y7az7ZiLEeGOvpP1fVrVNA"] = ["Training Materials","process.openup.base/capabilitypatterns/training_materials_339024C6.html"];
contentPage.processPage.elementUrls["_aJ1X4No7EdyzZqGyZ7hwdw"] = ["Build","process.openup.base/capabilitypatterns/build_309F83F9.html"];
contentPage.processPage.elementUrls["_DaTjoplXEeGlkdGl1HQlDA"] = ["Backout Plan","process.openup.base/capabilitypatterns/backout_plan_31075C71.html"];
contentPage.processPage.elementUrls["_N4ca8UVEEeK93ZZqiMLBsA"] = ["Implementation","process.openup.base/capabilitypatterns/implementation_204A0783.html"];
contentPage.processPage.elementUrls["_SKnA0uL9EdyM47cGD2jiaQ"] = ["Elaboration Iteration [1..n]","practice.mgmt.risk_value_lifecycle.base/capabilitypatterns/elaboration_iteration_88C5F333.html"];
contentPage.processPage.elementUrls["_y7a0H5iLEeGOvpP1fVrVNA"] = ["Release Communications","process.openup.base/capabilitypatterns/release_communications_2572D0E6.html"];
contentPage.processPage.elementUrls["_y7a0I5iLEeGOvpP1fVrVNA"] = ["Release","process.openup.base/capabilitypatterns/release_EA04B305.html"];
contentPage.processPage.elementUrls["__r658VThEd2ZeY-22kx0mw"] = ["Construction Phase","practice.mgmt.risk_value_lifecycle.base/capabilitypatterns/construction_phase_E35610BE.html"];
contentPage.processPage.elementUrls["_N7fH4UVEEeK93ZZqiMLBsA"] = ["Build","process.openup.base/capabilitypatterns/build_D50F56CE.html"];
contentPage.processPage.elementUrls["_DZttxZlXEeGlkdGl1HQlDA"] = ["Deployment Plan","process.openup.base/capabilitypatterns/deployment_plan_D0432255.html"];
contentPage.processPage.elementUrls["_y7a0JpiLEeGOvpP1fVrVNA"] = ["Release Controls","process.openup.base/capabilitypatterns/release_controls_45BCBF5F.html"];
contentPage.processPage.elementUrls["_8--9sZigEeGlkdGl1HQlDA"] = ["Develop Product Documentation and Training","process.openup.base/capabilitypatterns/prepare_product_documentation_6F4074F7.html"];
contentPage.processPage.elementUrls["_y7kkkZiLEeGOvpP1fVrVNA"] = ["Support Documentation","process.openup.base/capabilitypatterns/support_documentation_2088B879.html"];
contentPage.processPage.elementUrls["_y7a0BpiLEeGOvpP1fVrVNA"] = ["Deployment Plan","process.openup.base/capabilitypatterns/deployment_plan_212DAE67.html"];
contentPage.processPage.elementUrls["_y1MMMNOJEdyqlogshP8l4g"] = ["Iteration Plan","process.openup.base/capabilitypatterns/iteration_plan_5D6BAD68.html"];
contentPage.processPage.elementUrls["_-iix4dOOEdyqlogshP8l4g"] = ["Develop Solution Increment","process.openup.base/capabilitypatterns/develop_solution_8E22EA8F.html"];
contentPage.processPage.elementUrls["_OAQTIUVEEeK93ZZqiMLBsA"] = ["Implementation","process.openup.base/capabilitypatterns/implementation_9D3C3443.html"];
contentPage.processPage.elementUrls["_N7tKUUVEEeK93ZZqiMLBsA"] = ["Project Plan","process.openup.base/capabilitypatterns/project_plan_3FB65B42.html"];
contentPage.processPage.elementUrls["_4ouDUdOEEdyqlogshP8l4g"] = ["Agree on Technical Approach","process.openup.base/capabilitypatterns/agree_technical_approach_7096F6A3.html"];
contentPage.processPage.elementUrls["_FJm0gZoPEeGnJt_Qpwdfdg"] = ["Build","process.openup.base/capabilitypatterns/build_6CC79529.html"];
contentPage.processPage.elementUrls["_y7a0KZiLEeGOvpP1fVrVNA"] = ["Verify Successful Deployment","process.openup.base/capabilitypatterns/verify_successful_deployment_1BB58D68.html"];
contentPage.processPage.elementUrls["_N22fgUVEEeK93ZZqiMLBsA"] = ["Developer Test","process.openup.base/capabilitypatterns/developer_test_CC3A80C8.html"];
contentPage.processPage.elementUrls["_NyarcUVEEeK93ZZqiMLBsA"] = ["Tester","process.openup.base/capabilitypatterns/tester_6311FF90.html"];
contentPage.processPage.elementUrls["_N33zMUVEEeK93ZZqiMLBsA"] = ["Project Manager","process.openup.base/capabilitypatterns/project_manager_DAF3F896.html"];
contentPage.processPage.elementUrls["_N8ktAUVEEeK93ZZqiMLBsA"] = ["Design","process.openup.base/capabilitypatterns/design_BC82C4E9.html"];
contentPage.processPage.elementUrls["_NyPFQUVEEeK93ZZqiMLBsA"] = ["Architecture Notebook","process.openup.base/capabilitypatterns/architecture_notebook_D5C80FE7.html"];
contentPage.processPage.elementUrls["_y7az8piLEeGOvpP1fVrVNA"] = ["Provide Product Training","process.openup.base/capabilitypatterns/provide_product_training_E6BB1AFB.html"];
contentPage.processPage.elementUrls["_nm0swFTiEd2ZeY-22kx0mw"] = ["Product Release Milestone","practice.mgmt.risk_value_lifecycle.base/capabilitypatterns/Product Release Milestone_96CC0AE0.html"];
contentPage.processPage.elementUrls["_GQejYdOOEdyqlogshP8l4g"] = ["Ongoing Tasks","process.openup.base/capabilitypatterns/ongoing_tasks_949DD70E.html"];
contentPage.processPage.elementUrls["_OARhQUVEEeK93ZZqiMLBsA"] = ["Design","process.openup.base/capabilitypatterns/design_BABCBEAE.html"];
contentPage.processPage.elementUrls["_N5duoUVEEeK93ZZqiMLBsA"] = ["Developer","process.openup.base/capabilitypatterns/developer_612C0B20.html"];
contentPage.processPage.elementUrls["_y7a0IJiLEeGOvpP1fVrVNA"] = ["Execute Deployment Plan","process.openup.base/capabilitypatterns/execute_deployment_plan_87F3E91A.html"];
contentPage.processPage.elementUrls["_N9ItsUVEEeK93ZZqiMLBsA"] = ["Any Role","process.openup.base/capabilitypatterns/any_role_6A1B6BDA.html"];
contentPage.processPage.elementUrls["_EOm5oNOLEdyqlogshP8l4g"] = ["Identify and Outline Requirements","process.openup.base/capabilitypatterns/identify_and_outline_requirements_FF8708A2.html"];
contentPage.processPage.elementUrls["_Nx344UVEEeK93ZZqiMLBsA"] = ["System-Wide Requirements","process.openup.base/capabilitypatterns/system_wide_requirements_D158548E.html"];
contentPage.processPage.elementUrls["_EfWx0FQ0Ed2i9JHp7xurvw"] = ["Initial Operational Capability Milestone","process.openup.base/deliveryprocesses/initial_operational_capability_milestone_B0ADAE04.html"];
contentPage.processPage.elementUrls["_XayTQdOOEdyqlogshP8l4g"] = ["Plan and Manage Iteration","process.openup.base/capabilitypatterns/plan_manage_iteration_947FDB8B.html"];
contentPage.processPage.elementUrls["_y7kkk5iLEeGOvpP1fVrVNA"] = ["Product Documentation","process.openup.base/capabilitypatterns/product_documentation_77FBA254.html"];
contentPage.processPage.elementUrls["_Nz-KoUVEEeK93ZZqiMLBsA"] = ["Test Case","process.openup.base/capabilitypatterns/test_case_44AD1ED2.html"];
contentPage.processPage.elementUrls["_N4_0kUVEEeK93ZZqiMLBsA"] = ["Deployment Engineer","process.openup.base/capabilitypatterns/deployment_engineer_4D360443.html"];
contentPage.processPage.elementUrls["_y1MMMtOJEdyqlogshP8l4g"] = ["Work Items List","process.openup.base/capabilitypatterns/work_items_list_56A2A18E.html"];
contentPage.processPage.elementUrls["_Nyu0gUVEEeK93ZZqiMLBsA"] = ["Developer Test","process.openup.base/capabilitypatterns/developer_test_881113B6.html"];
contentPage.processPage.elementUrls["_N8TAMUVEEeK93ZZqiMLBsA"] = ["Use Case","process.openup.base/capabilitypatterns/use_case_2ADDA261.html"];
contentPage.processPage.elementUrls["_N4L8QUVEEeK93ZZqiMLBsA"] = ["Iteration Plan","process.openup.base/capabilitypatterns/iteration_plan_92B53218.html"];
contentPage.processPage.elementUrls["_3MJwMZoQEeGnJt_Qpwdfdg"] = ["Tailor the Process","process.openup.base/capabilitypatterns/tailor_process_58D0DC84.html"];
contentPage.processPage.elementUrls["_3MJwNpoQEeGnJt_Qpwdfdg"] = ["Tools","process.openup.base/capabilitypatterns/tools_BFBD2B9.html"];
contentPage.processPage.elementUrls["_N8NgoUVEEeK93ZZqiMLBsA"] = ["Stakeholder","process.openup.base/capabilitypatterns/stakeholder_5FBD26EB.html"];
contentPage.processPage.elementUrls["_y7az8ZiLEeGOvpP1fVrVNA"] = ["Deliver end user Training","process.openup.base/capabilitypatterns/deliver_end_user_training_F82206E5.html"];
contentPage.processPage.elementUrls["_t7pDUNOJEdyqlogshP8l4g"] = ["Plan Project","process.openup.base/capabilitypatterns/plan_the_project_9D16B97F.html"];
contentPage.processPage.elementUrls["_oaK10JigEeGlkdGl1HQlDA"] = ["Deployment Plan","process.openup.base/capabilitypatterns/deployment_plan_1FE56E41.html"];
contentPage.processPage.elementUrls["_NykccUVEEeK93ZZqiMLBsA"] = ["Test Script","process.openup.base/capabilitypatterns/test_script_6268A4F7.html"];
contentPage.processPage.elementUrls["_y7a0GZiLEeGOvpP1fVrVNA"] = ["Deploy Release to Production","process.openup.base/capabilitypatterns/deploy_release_to_production_96E04EC.html"];
contentPage.processPage.elementUrls["_RQi0AdONEdyqlogshP8l4g"] = ["Construction Phase Iteration","process.openup.base/capabilitypatterns/construction_phase_iteration_9AC1727C.html"];
contentPage.processPage.elementUrls["_N2wY4UVEEeK93ZZqiMLBsA"] = ["Vision","process.openup.base/capabilitypatterns/vision_A0224569.html"];
contentPage.processPage.elementUrls["_0Qiv4NOJEdyqlogshP8l4g"] = ["Assess Results","process.openup.base/capabilitypatterns/assess_results_A8262B77.html"];
contentPage.processPage.elementUrls["_6R37Mt_1EdyOsumnGvWsEg"] = ["[Technical Implementation]","process.openup.base/capabilitypatterns/technical_implementation_slot_72D15E9D.html"];
contentPage.processPage.elementUrls["_Nxjv0UVEEeK93ZZqiMLBsA"] = ["Iteration Plan","process.openup.base/capabilitypatterns/iteration_plan_88C30E3D.html"];
contentPage.processPage.elementUrls["_OAPFAUVEEeK93ZZqiMLBsA"] = ["Developer Test","process.openup.base/capabilitypatterns/developer_test_51B9F45E.html"];
contentPage.processPage.elementUrls["_N7OCIUVEEeK93ZZqiMLBsA"] = ["Architect","process.openup.base/capabilitypatterns/architect_2128B80B.html"];
contentPage.processPage.elementUrls["_hVe-oNOKEdyqlogshP8l4g"] = ["Implement Solution","process.openup.base/capabilitypatterns/implement_solution_B7C117A5.html"];
contentPage.processPage.elementUrls["_EOwqqdOLEdyqlogshP8l4g"] = ["Use-Case Model","process.openup.base/capabilitypatterns/use_case_model_B78529E8.html"];
contentPage.processPage.elementUrls["_y7a0A5iLEeGOvpP1fVrVNA"] = ["Infrastructure","process.openup.base/capabilitypatterns/infrastructure_C575A20D.html"];
contentPage.processPage.elementUrls["_N5HJUUVEEeK93ZZqiMLBsA"] = ["Backout Plan","process.openup.base/capabilitypatterns/backout_plan_8909362B.html"];
contentPage.processPage.elementUrls["_N7fu8UVEEeK93ZZqiMLBsA"] = ["Design","process.openup.base/capabilitypatterns/design_E4A0E37.html"];
contentPage.processPage.elementUrls["_Nz4rEUVEEeK93ZZqiMLBsA"] = ["Architecture Notebook","process.openup.base/capabilitypatterns/architecture_notebook_AF1FC6BC.html"];
contentPage.processPage.elementUrls["_DZttw5lXEeGlkdGl1HQlDA"] = ["Developer","process.openup.base/capabilitypatterns/developer_63242A11.html"];
contentPage.processPage.elementUrls["_N7eg0UVEEeK93ZZqiMLBsA"] = ["Implementation","process.openup.base/capabilitypatterns/implementation_C2C7CE52.html"];
contentPage.processPage.elementUrls["_y7a0AJiLEeGOvpP1fVrVNA"] = ["Develop Release Communications","process.openup.base/capabilitypatterns/develop_release_communications_6364D822.html"];
contentPage.processPage.elementUrls["_OAQ6MUVEEeK93ZZqiMLBsA"] = ["Build","process.openup.base/capabilitypatterns/build_958C4821.html"];
contentPage.processPage.elementUrls["_N0XMMUVEEeK93ZZqiMLBsA"] = ["Glossary","process.openup.base/capabilitypatterns/glossary_899E4E1.html"];
contentPage.processPage.elementUrls["_N4dpEUVEEeK93ZZqiMLBsA"] = ["Build","process.openup.base/capabilitypatterns/build_105013C4.html"];
contentPage.processPage.elementUrls["_Ny0UEUVEEeK93ZZqiMLBsA"] = ["Design","process.openup.base/capabilitypatterns/design_B7B264E2.html"];
contentPage.processPage.elementUrls["_TV_k8dOKEdyqlogshP8l4g"] = ["Develop Solution Increment","process.openup.base/capabilitypatterns/develop_solution_4A08A92A.html"];
contentPage.processPage.elementUrls["_N8RyEUVEEeK93ZZqiMLBsA"] = ["Glossary","process.openup.base/capabilitypatterns/glossary_345046E3.html"];
contentPage.processPage.elementUrls["_EOwqqNOLEdyqlogshP8l4g"] = ["Glossary","process.openup.base/capabilitypatterns/glossary_C8EC15D2.html"];
contentPage.processPage.elementUrls["_Nx5HAUVEEeK93ZZqiMLBsA"] = ["Use-Case Model","process.openup.base/capabilitypatterns/use_case_model_AD541FF3.html"];
contentPage.processPage.elementUrls["_dC4w4JojEd2XAqcHTC2Siw"] = ["Implementation","process.openup.base/capabilitypatterns/implementation_1DA9E76A.html"];
contentPage.processPage.elementUrls["_aUsVEdONEdyqlogshP8l4g"] = ["Elaboration Phase Iteration","process.openup.base/capabilitypatterns/elaboration_phase_iteration_54DFA2A9.html"];
contentPage.processPage.elementUrls["_NxmMEEVEEeK93ZZqiMLBsA"] = ["Work Items List","process.openup.base/capabilitypatterns/work_items_list_64B895EC.html"];
contentPage.processPage.elementUrls["_N4NKYUVEEeK93ZZqiMLBsA"] = ["Risk List","process.openup.base/capabilitypatterns/risk_list_CA2D3121.html"];
contentPage.processPage.elementUrls["_HDOWUNOLEdyqlogshP8l4g"] = ["Create Test Cases","process.openup.base/capabilitypatterns/create_test_cases_3D5E914E.html"];
contentPage.processPage.elementUrls["_y05RQNOJEdyqlogshP8l4g"] = ["Plan Iteration","process.openup.base/capabilitypatterns/plan_iteration_B0421040.html"];
contentPage.processPage.elementUrls["_NxYwsUVEEeK93ZZqiMLBsA"] = ["Project Manager","process.openup.base/capabilitypatterns/project_manager_66DC61CC.html"];
contentPage.processPage.elementUrls["_N6V4YUVEEeK93ZZqiMLBsA"] = ["Architecture Notebook","process.openup.base/capabilitypatterns/architecture_notebook_A61F06C4.html"];
contentPage.processPage.elementUrls["_N2X-YUVEEeK93ZZqiMLBsA"] = ["Work Items List","process.openup.base/capabilitypatterns/work_items_list_A3563137.html"];
contentPage.processPage.elementUrls["_N8LrcUVEEeK93ZZqiMLBsA"] = ["Tester","process.openup.base/capabilitypatterns/tester_2FF51404.html"];
contentPage.processPage.elementUrls["_N2lZwEVEEeK93ZZqiMLBsA"] = ["Architecture Notebook","process.openup.base/capabilitypatterns/architecture_notebook_E168BF22.html"];
contentPage.processPage.elementUrls["_N8RyFEVEEeK93ZZqiMLBsA"] = ["System-Wide Requirements","process.openup.base/capabilitypatterns/system_wide_requirements_EE4448F2.html"];
contentPage.processPage.elementUrls["_y7a0ApiLEeGOvpP1fVrVNA"] = ["Install and Validate Infrastructure","process.openup.base/capabilitypatterns/install_validate_infrastructure_5C9BCC48.html"];
contentPage.processPage.elementUrls["_BBN48VTiEd2ZeY-22kx0mw"] = ["Transition Phase","practice.mgmt.risk_value_lifecycle.base/capabilitypatterns/transition_phase_8CDF05F3.html"];
contentPage.processPage.elementUrls["_YwLY4dOOEdyqlogshP8l4g"] = ["Identify and Refine Requirements","process.openup.base/capabilitypatterns/identify_and_refine_requirements_38854BCF.html"];
contentPage.processPage.elementUrls["_sopKYNOJEdyqlogshP8l4g"] = ["Develop Technical Vision","process.openup.base/capabilitypatterns/develop_technical_vision_89F6E7DB.html"];
contentPage.processPage.elementUrls["_N6DkgUVEEeK93ZZqiMLBsA"] = ["Use Case","process.openup.base/capabilitypatterns/use_case_4C53523F.html"];
contentPage.processPage.elementUrls["_NyhZIUVEEeK93ZZqiMLBsA"] = ["Test Case","process.openup.base/capabilitypatterns/test_case_79B4BAEB.html"];
contentPage.processPage.elementUrls["_N2Ts8UVEEeK93ZZqiMLBsA"] = ["Architect","process.openup.base/capabilitypatterns/architect_EA976C82.html"];
contentPage.processPage.elementUrls["_N0V-EUVEEeK93ZZqiMLBsA"] = ["Vision","process.openup.base/capabilitypatterns/vision_5F7AEF0B.html"];
contentPage.processPage.elementUrls["_OADe0UVEEeK93ZZqiMLBsA"] = ["Developer","process.openup.base/capabilitypatterns/developer_5015BA3A.html"];
contentPage.processPage.elementUrls["_N0ZBYUVEEeK93ZZqiMLBsA"] = ["System-Wide Requirements","process.openup.base/capabilitypatterns/system_wide_requirements_3861F7C8.html"];
contentPage.processPage.elementUrls["_Vi5r8tOLEdyqlogshP8l4g"] = ["[Technical Implementation]","process.openup.base/capabilitypatterns/technical_implementation_slot_4A0321FD.html"];
contentPage.processPage.elementUrls["_FJm0hJoPEeGnJt_Qpwdfdg"] = ["Design","process.openup.base/capabilitypatterns/design_26BB9738.html"];
contentPage.processPage.elementUrls["_N8SZIUVEEeK93ZZqiMLBsA"] = ["Use-Case Model","process.openup.base/capabilitypatterns/use_case_model_4697CF5F.html"];
contentPage.processPage.elementUrls["_NxW7gUVEEeK93ZZqiMLBsA"] = ["Analyst","process.openup.base/capabilitypatterns/analyst_F629AB5A.html"];
contentPage.processPage.elementUrls["_pOgXIVQwEd2i9JHp7xurvw"] = ["Transition Phase","process.openup.base/deliveryprocesses/Transition Phase_14EE9310.html"];
contentPage.processPage.elementUrls["_soyUVNOJEdyqlogshP8l4g"] = ["Vision","process.openup.base/capabilitypatterns/vision_69999C5F.html"];
contentPage.processPage.elementUrls["_HGqkMNnTEdyNj6EOmqy5Rg"] = ["Request Change","process.openup.base/capabilitypatterns/request_change_BA075BFE.html"];
contentPage.processPage.elementUrls["_y7az7piLEeGOvpP1fVrVNA"] = ["Deliver Support Training","process.openup.base/capabilitypatterns/deliver_support_training_222938DC.html"];
contentPage.processPage.elementUrls["_y7a0JJiLEeGOvpP1fVrVNA"] = ["Backout Plan","process.openup.base/capabilitypatterns/backout_plan_4C85CB39.html"];
contentPage.processPage.elementUrls["_N-194UVEEeK93ZZqiMLBsA"] = ["Build","process.openup.base/capabilitypatterns/build_5598A3CA.html"];
contentPage.processPage.elementUrls["_N6CWYUVEEeK93ZZqiMLBsA"] = ["Use-Case Model","process.openup.base/capabilitypatterns/use_case_model_93677B1A.html"];
contentPage.processPage.elementUrls["_h0Gs8dONEdyqlogshP8l4g"] = ["Inception Phase Iteration","process.openup.base/capabilitypatterns/inception_phase_iteration_B1800053.html"];
contentPage.processPage.elementUrls["_yw_dcZlVEeGlkdGl1HQlDA"] = ["Identify and Refine Requirements","process.openup.base/capabilitypatterns/identify_and_refine_requirements_68AB81F5.html"];
contentPage.processPage.elementUrls["_y7az8JiLEeGOvpP1fVrVNA"] = ["Product Documentation","process.openup.base/capabilitypatterns/product_documentation_ED8426D5.html"];
contentPage.processPage.elementUrls["_y7az75iLEeGOvpP1fVrVNA"] = ["User Documentation","process.openup.base/capabilitypatterns/user_documentation_8B030EA1.html"];
contentPage.processPage.elementUrls["_gX7xQtOKEdyqlogshP8l4g"] = ["Developer Test","process.openup.base/capabilitypatterns/developer_test_DC61DB05.html"];
contentPage.processPage.elementUrls["_N8i30UVEEeK93ZZqiMLBsA"] = ["Implementation","process.openup.base/capabilitypatterns/implementation_A74C421B.html"];
contentPage.processPage.elementUrls["_SKnA1uL9EdyM47cGD2jiaQ"] = ["Risk-Value Lifecycle Phases","practice.mgmt.risk_value_lifecycle.base/capabilitypatterns/risk_value_lifecycle_phases_4D57D552.html"];
contentPage.processPage.elementUrls["_N26J4UVEEeK93ZZqiMLBsA"] = ["Design","process.openup.base/capabilitypatterns/design_C30F1CFB.html"];
contentPage.processPage.elementUrls["_y7a0J5iLEeGOvpP1fVrVNA"] = ["Deployment Plan","process.openup.base/capabilitypatterns/deployment_plan_AE969524.html"];
contentPage.processPage.elementUrls["_FJm0e5oPEeGnJt_Qpwdfdg"] = ["Developer Test","process.openup.base/capabilitypatterns/developer_test_3B16BAC6.html"];
contentPage.processPage.elementUrls["_N-0vwUVEEeK93ZZqiMLBsA"] = ["Developer Test","process.openup.base/capabilitypatterns/developer_test_E1BE4685.html"];
contentPage.processPage.elementUrls["_SKnAzuL9EdyM47cGD2jiaQ"] = ["Inception Iteration [1..n]","practice.mgmt.risk_value_lifecycle.base/capabilitypatterns/inception_iteration_5AF15029.html"];
contentPage.processPage.elementUrls["_EjG_cNOKEdyqlogshP8l4g"] = ["Architecture Notebook","process.openup.base/capabilitypatterns/architecture_notebook_1EE52118.html"];
contentPage.processPage.elementUrls["_NywCoUVEEeK93ZZqiMLBsA"] = ["Implementation","process.openup.base/capabilitypatterns/implementation_BF8912BF.html"];
contentPage.processPage.elementUrls["_N6AhMUVEEeK93ZZqiMLBsA"] = ["Glossary","process.openup.base/capabilitypatterns/glossary_359DB2B9.html"];
contentPage.processPage.elementUrls["_N39SxEVEEeK93ZZqiMLBsA"] = ["Glossary","process.openup.base/capabilitypatterns/glossary_EDAD358E.html"];
contentPage.processPage.elementUrls["_n75CddfeEdy8T_PKWvNDBA"] = ["[Technical Specification]","process.openup.base/capabilitypatterns/technical_specification_slot_7136EBED.html"];
contentPage.processPage.elementUrls["_y7az_piLEeGOvpP1fVrVNA"] = ["Review and Conform to Release Controls","process.openup.base/capabilitypatterns/review_conform_to_release_controls_D8F48DB4.html"];
contentPage.processPage.elementUrls["_sjccUN_1EdyOsumnGvWsEg"] = ["Envision the Architecture","process.openup.base/capabilitypatterns/envision_the_arch_A1FEF666.html"];
contentPage.processPage.elementUrls["_Viv68NOLEdyqlogshP8l4g"] = ["Implement Tests","process.openup.base/capabilitypatterns/implement_tests_ECF4B2BA.html"];
contentPage.processPage.elementUrls["_EOwqp9OLEdyqlogshP8l4g"] = ["Use Case","process.openup.base/capabilitypatterns/use_case_666AFD9E.html"];
contentPage.processPage.elementUrls["_Nzu6EUVEEeK93ZZqiMLBsA"] = ["Developer","process.openup.base/capabilitypatterns/developer_4B484B9F.html"];
contentPage.processPage.elementUrls["_N7P3UUVEEeK93ZZqiMLBsA"] = ["Developer","process.openup.base/capabilitypatterns/developer_64FB0BCE.html"];
contentPage.processPage.elementUrls["_2_nRIVThEd2ZeY-22kx0mw"] = ["Elaboration Phase","practice.mgmt.risk_value_lifecycle.base/capabilitypatterns/elaboration_phase_53DE05EC.html"];
contentPage.processPage.elementUrls["_N7r8MUVEEeK93ZZqiMLBsA"] = ["Work Items List","process.openup.base/capabilitypatterns/work_items_list_83E5C39.html"];
contentPage.processPage.elementUrls["_y7az65iLEeGOvpP1fVrVNA"] = ["Support Documentation","process.openup.base/capabilitypatterns/support_documentation_C6712C82.html"];
contentPage.processPage.elementUrls["_N-weUUVEEeK93ZZqiMLBsA"] = ["Developer","process.openup.base/capabilitypatterns/developer_5BF034EF.html"];
contentPage.processPage.elementUrls["_N_CLIUVEEeK93ZZqiMLBsA"] = ["Deployment Engineer","process.openup.base/capabilitypatterns/deployment_engineer_78767788.html"];
contentPage.processPage.elementUrls["_8tQrUVQvEd2i9JHp7xurvw"] = ["Inception Phase","process.openup.base/deliveryprocesses/Inception Phase_5229EC90.html"];
contentPage.processPage.elementUrls["_nfpeAdOOEdyqlogshP8l4g"] = ["Initiate Project","process.openup.base/capabilitypatterns/initiate_project_9D7C8344.html"];
contentPage.processPage.elementUrls["_N0B1AEVEEeK93ZZqiMLBsA"] = ["Test Script","process.openup.base/capabilitypatterns/test_script_609A4E17.html"];
contentPage.processPage.elementUrls["__ZInMdOEEdyqlogshP8l4g"] = ["Ongoing Tasks","process.openup.base/capabilitypatterns/ongoing_tasks_CA154C21.html"];
contentPage.processPage.elementUrls["_N-1W0UVEEeK93ZZqiMLBsA"] = ["Implementation","process.openup.base/capabilitypatterns/implementation_5D488FEC.html"];
contentPage.processPage.elementUrls["_N8M5lEVEEeK93ZZqiMLBsA"] = ["Developer","process.openup.base/capabilitypatterns/developer_F480B26D.html"];
contentPage.processPage.elementUrls["_NzwIMUVEEeK93ZZqiMLBsA"] = ["Stakeholder","process.openup.base/capabilitypatterns/stakeholder_82C04AA8.html"];
contentPage.processPage.elementUrls["_N0bdoUVEEeK93ZZqiMLBsA"] = ["Use Case","process.openup.base/capabilitypatterns/use_case_AA9B150C.html"];
contentPage.processPage.elementUrls["_N8kF8UVEEeK93ZZqiMLBsA"] = ["Build","process.openup.base/capabilitypatterns/build_DEC44124.html"];
contentPage.processPage.elementUrls["_Dlo8wNo8EdyzZqGyZ7hwdw"] = ["Integrate and Create Build","process.openup.base/capabilitypatterns/integrate_and_create_build_CFB94658.html"];
contentPage.processPage.elementUrls["_N5qi8UVEEeK93ZZqiMLBsA"] = ["Test Case","process.openup.base/capabilitypatterns/test_case_450FC43E.html"];
contentPage.processPage.elementUrls["_Vi5r8dOLEdyqlogshP8l4g"] = ["Test Script","process.openup.base/capabilitypatterns/test_script_3F6541ED.html"];
contentPage.processPage.elementUrls["_SKnAxOL9EdyM47cGD2jiaQ"] = ["Transition Iteration [1..n]","practice.mgmt.risk_value_lifecycle.base/capabilitypatterns/transition_iteration_D89697C5.html"];
contentPage.processPage.elementUrls["_RXGoodOFEdyqlogshP8l4g"] = ["Develop Solution Increment","process.openup.base/capabilitypatterns/develop_solution_4FBB0E6E.html"];
contentPage.processPage.elementUrls["_N5_6IUVEEeK93ZZqiMLBsA"] = ["Vision","process.openup.base/capabilitypatterns/vision_106D3C2C.html"];
contentPage.processPage.elementUrls["_N2eFAUVEEeK93ZZqiMLBsA"] = ["Test Script","process.openup.base/capabilitypatterns/test_script_E846CFB.html"];
contentPage.processPage.elementUrls["_N2Se0UVEEeK93ZZqiMLBsA"] = ["Analyst","process.openup.base/capabilitypatterns/analyst_9F152C9D.html"];
contentPage.processPage.elementUrls["_y7a0BJiLEeGOvpP1fVrVNA"] = ["Backout Plan","process.openup.base/capabilitypatterns/backout_plan_27F6BA41.html"];
contentPage.processPage.elementUrls["_HhjJsdOOEdyqlogshP8l4g"] = ["Test Solution","process.openup.base/capabilitypatterns/test_solution_48F8F25.html"];
contentPage.processPage.elementUrls["_LxTaQNnGEdyNWvE4rz3mXQ"] = ["[Technical Specification]","process.openup.base/capabilitypatterns/technical_specification_slot_DDD377AB.html"];
contentPage.processPage.elementUrls["_ybaHoZlYEeGlkdGl1HQlDA"] = ["Finalize Product Documentation and Training","process.openup.base/capabilitypatterns/prep_doc_trng_F5293239.html"];
contentPage.processPage.elementUrls["_NxYJoUVEEeK93ZZqiMLBsA"] = ["Architect","process.openup.base/capabilitypatterns/architect_2DA1AA63.html"];
contentPage.processPage.elementUrls["_gX7xQdOKEdyqlogshP8l4g"] = ["[Technical Design]","process.openup.base/capabilitypatterns/technical_design_slot_D1C3FAF5.html"];
contentPage.processPage.elementUrls["_N7quEUVEEeK93ZZqiMLBsA"] = ["Iteration Plan","process.openup.base/capabilitypatterns/iteration_plan_FDA6BFDF.html"];
contentPage.processPage.elementUrls["_N04JkUVEEeK93ZZqiMLBsA"] = ["Process Engineer","process.openup.base/capabilitypatterns/process_engineer_15F119E4.html"];
contentPage.processPage.elementUrls["_N-BegUVEEeK93ZZqiMLBsA"] = ["Design","process.openup.base/capabilitypatterns/design_39B0B972.html"];
contentPage.processPage.elementUrls["_WttSMdOLEdyqlogshP8l4g"] = ["Test Log","process.openup.base/capabilitypatterns/test_log_89A700A4.html"];
contentPage.processPage.elementUrls["_XJ0u0FTiEd2ZeY-22kx0mw"] = ["Lifecycle Architecture Milestone","practice.mgmt.risk_value_lifecycle.base/capabilitypatterns/Lifecycle Architecture Milestone_65437D7C.html"];
contentPage.processPage.elementUrls["_w-Bc8dOOEdyqlogshP8l4g"] = ["Agree on Technical Approach","process.openup.base/capabilitypatterns/agree_technical_approach_66972D77.html"];
contentPage.processPage.elementUrls["_ieYHIVQwEd2i9JHp7xurvw"] = ["Elaboration Phase","process.openup.base/deliveryprocesses/Elaboration Phase_F6EBBC8B.html"];
contentPage.processPage.elementUrls["_6RuKMN_1EdyOsumnGvWsEg"] = ["Refine the Architecture","process.openup.base/capabilitypatterns/refine_the_arch_42A35209.html"];
contentPage.processPage.elementUrls["_N5gK4UVEEeK93ZZqiMLBsA"] = ["Architect","process.openup.base/capabilitypatterns/architect_C7E676E.html"];
contentPage.processPage.elementUrls["_N4NxcUVEEeK93ZZqiMLBsA"] = ["Work Items List","process.openup.base/capabilitypatterns/work_items_list_9ED33544.html"];
contentPage.processPage.elementUrls["_3s7aYdONEdyqlogshP8l4g"] = ["Plan and Manage Iteration","process.openup.base/capabilitypatterns/plan_manage_iteration_8A8E7EA8.html"];
contentPage.processPage.elementUrls["_KaeNsdOFEdyqlogshP8l4g"] = ["Develop the Architecture","process.openup.base/capabilitypatterns/develop_architecture_C7BBA35B.html"];
contentPage.processPage.elementUrls["_OpsH8GpmEd24CboUCnKL3A"] = ["Glossary","process.openup.base/capabilitypatterns/glossary_559BC141.html"];
contentPage.processPage.elementUrls["_y7az_ZiLEeGOvpP1fVrVNA"] = ["Release Communications","process.openup.base/capabilitypatterns/release_communications_EA5B799E.html"];
contentPage.processPage.elementUrls["_N34aQUVEEeK93ZZqiMLBsA"] = ["Stakeholder","process.openup.base/capabilitypatterns/stakeholder_BF39CB98.html"];
contentPage.processPage.elementUrls["_Vi5r8NOLEdyqlogshP8l4g"] = ["Test Case","process.openup.base/capabilitypatterns/test_case_50CC2DD7.html"];
contentPage.processPage.elementUrls["_o1WpwZoQEeGnJt_Qpwdfdg"] = ["Prepare Environment","process.openup.base/capabilitypatterns/Prepare Environment_E2EC0F4E.html"];
contentPage.processPage.elementUrls["_wU5YkG7rEd2yFK8n6tDvyw"] = ["[Project Work]","process.openup.base/capabilitypatterns/project_work_slot_B5F50387.html"];
contentPage.processPage.elementUrls["_frh-QNOKEdyqlogshP8l4g"] = ["[Technical Architecture]","process.openup.base/capabilitypatterns/technical_architecture_slot_B93D7FFE.html"];
contentPage.processPage.elementUrls["_N8M5kUVEEeK93ZZqiMLBsA"] = ["Analyst","process.openup.base/capabilitypatterns/analyst_3A8CB05E.html"];
contentPage.processPage.elementUrls["_Nztr8UVEEeK93ZZqiMLBsA"] = ["Architect","process.openup.base/capabilitypatterns/architect_9C2CE2E9.html"];
contentPage.processPage.elementUrls["_OAEs8UVEEeK93ZZqiMLBsA"] = ["Deployment Engineer","process.openup.base/capabilitypatterns/deployment_engineer_9B97FA1F.html"];
contentPage.processPage.elementUrls["_Nzsd0UVEEeK93ZZqiMLBsA"] = ["Analyst","process.openup.base/capabilitypatterns/analyst_50AAA304.html"];
contentPage.processPage.elementUrls["_WttSMNOLEdyqlogshP8l4g"] = ["Run Tests","process.openup.base/capabilitypatterns/run_tests_9B0DEC8E.html"];
contentPage.processPage.elementUrls["_N-AQYUVEEeK93ZZqiMLBsA"] = ["Implementation","process.openup.base/capabilitypatterns/implementation_80C4E24D.html"];
contentPage.processPage.elementUrls["_5v_o4dOOEdyqlogshP8l4g"] = ["Plan and Manage Iteration","process.openup.base/capabilitypatterns/plan_manage_iteration_1EC56795.html"];
contentPage.processPage.elementUrls["_ILZlwFQ0Ed2i9JHp7xurvw"] = ["Product Release Milestone","process.openup.base/deliveryprocesses/product_release_milestone_1A9A4E10.html"];
contentPage.processPage.elementUrls["_xxcpgdOEEdyqlogshP8l4g"] = ["Identify and Refine Requirements","process.openup.base/capabilitypatterns/identify_and_refine_requirements_7FA6CB14.html"];
contentPage.processPage.elementUrls["_FX7SINOLEdyqlogshP8l4g"] = ["Detail Use-Case Scenarios","process.openup.base/capabilitypatterns/detail_use_case_scenarios_79A10C4.html"];
contentPage.processPage.elementUrls["_eyv_UdOOEdyqlogshP8l4g"] = ["Develop Solution Increment","process.openup.base/capabilitypatterns/develop_solution_C9559260.html"];
contentPage.processPage.elementUrls["_nfpBkVQwEd2i9JHp7xurvw"] = ["Construction Phase","process.openup.base/deliveryprocesses/Construction Phase_BD0D5748.html"];
contentPage.processPage.elementUrls["_kYVSUdOPEdyqlogshP8l4g"] = ["Inception Iteration [1..n]","process.openup.base/deliveryprocesses/inception_phase_iteration_1EFD4B4F.html"];
contentPage.processPage.elementUrls["_LxTaQdnGEdyNWvE4rz3mXQ"] = ["[Technical Test Results]","process.openup.base/capabilitypatterns/technical_test_results_slot_CC6C8BC1.html"];
contentPage.processPage.elementUrls["_Nxk98UVEEeK93ZZqiMLBsA"] = ["Risk List","process.openup.base/capabilitypatterns/risk_list_935AAA97.html"];
contentPage.processPage.elementUrls["_N7rVIUVEEeK93ZZqiMLBsA"] = ["Risk List","process.openup.base/capabilitypatterns/risk_list_FEE485B.html"];
contentPage.processPage.elementUrls["_NxZXwUVEEeK93ZZqiMLBsA"] = ["Stakeholder","process.openup.base/capabilitypatterns/stakeholder_7923EA48.html"];
contentPage.processPage.elementUrls["_NyY2QUVEEeK93ZZqiMLBsA"] = ["Developer","process.openup.base/capabilitypatterns/developer_E928F62A.html"];
contentPage.processPage.elementUrls["_y7kkkpiLEeGOvpP1fVrVNA"] = ["Develop User Documentation","process.openup.base/capabilitypatterns/develop_user_documentation_F21CC8F.html"];
contentPage.processPage.elementUrls["_N_uusUVEEeK93ZZqiMLBsA"] = ["Trainer","process.openup.base/capabilitypatterns/trainer_E64B1715.html"];
contentPage.processPage.elementUrls["_iRZNQNOKEdyqlogshP8l4g"] = ["Run Developer Tests","process.openup.base/capabilitypatterns/run_developer_tests_91CCE06A.html"];
contentPage.processPage.elementUrls["_-UFkUVThEd2ZeY-22kx0mw"] = ["Inception Phase","practice.mgmt.risk_value_lifecycle.base/capabilitypatterns/inception_phase_5078703C.html"];
contentPage.processPage.elementUrls["_CqFrgdOOEdyqlogshP8l4g"] = ["Develop Solution Increment","process.openup.base/capabilitypatterns/develop_solution_2E5A12EB.html"];
contentPage.processPage.elementUrls["_N-A3cUVEEeK93ZZqiMLBsA"] = ["Build","process.openup.base/capabilitypatterns/build_148042E5.html"];
contentPage.processPage.elementUrls["_N25i0UVEEeK93ZZqiMLBsA"] = ["Build","process.openup.base/capabilitypatterns/build_B0C7947F.html"];
contentPage.processPage.elementUrls["_OAm4cUVEEeK93ZZqiMLBsA"] = ["Product Owner","process.openup.base/capabilitypatterns/product_owner_347465AD.html"];
contentPage.processPage.elementUrls["_N31W8UVEEeK93ZZqiMLBsA"] = ["Architect","process.openup.base/capabilitypatterns/architect_CD6D61EA.html"];
contentPage.processPage.elementUrls["_Nz__0UVEEeK93ZZqiMLBsA"] = ["Test Log","process.openup.base/capabilitypatterns/test_log_33B1FAD3.html"];
contentPage.processPage.elementUrls["_3MJwMpoQEeGnJt_Qpwdfdg"] = ["Set Up Tools","process.openup.base/capabilitypatterns/setup_tools_4769F09A.html"];
contentPage.processPage.elementUrls["_ofSHoplWEeGlkdGl1HQlDA"] = ["Training Materials","process.openup.base/capabilitypatterns/training_materials_765C4469.html"];
contentPage.processPage.elementUrls["_SuWj4dOPEdyqlogshP8l4g"] = ["OpenUP Lifecycle","process.openup.base/deliveryprocesses/openup_lifecycle_EE511F3A.html"];
contentPage.processPage.elementUrls["_vyeP0dOOEdyqlogshP8l4g"] = ["Identify and Refine Requirements","process.openup.base/capabilitypatterns/identify_and_refine_requirements_E06651D6.html"];
contentPage.processPage.elementUrls["_gXo2UNOKEdyqlogshP8l4g"] = ["Implement Developer Tests","process.openup.base/capabilitypatterns/implement_developer_tests_6442995D.html"];
contentPage.processPage.elementUrls["_oaBE0JigEeGlkdGl1HQlDA"] = ["Outline Deployment Plan","process.openup.base/capabilitypatterns/plan_deployment_C8487FE.html"];
contentPage.processPage.elementUrls["_N32lEUVEEeK93ZZqiMLBsA"] = ["Analyst","process.openup.base/capabilitypatterns/analyst_8F71B8B1.html"];
contentPage.processPage.elementUrls["_f4VuYdOOEdyqlogshP8l4g"] = ["Test Solution","process.openup.base/capabilitypatterns/test_solution_B552446C.html"];
contentPage.processPage.elementUrls["_N3_vAUVEEeK93ZZqiMLBsA"] = ["Use Case","process.openup.base/capabilitypatterns/use_case_3D44B072.html"];
contentPage.processPage.elementUrls["_N2WJMUVEEeK93ZZqiMLBsA"] = ["Tester","process.openup.base/capabilitypatterns/tester_D12AD441.html"];
contentPage.processPage.elementUrls["_Nx6VIUVEEeK93ZZqiMLBsA"] = ["Use Case","process.openup.base/capabilitypatterns/use_case_F8D65FD8.html"];
contentPage.processPage.elementUrls["_3MJwM5oQEeGnJt_Qpwdfdg"] = ["Verify Tool Configuration and Installation","process.openup.base/capabilitypatterns/verify_tool_config_installation_B043C65F.html"];
contentPage.processPage.elementUrls["_y7kkkJiLEeGOvpP1fVrVNA"] = ["Develop Support Documentation","process.openup.base/capabilitypatterns/develop_support_documentation_15EAD869.html"];
contentPage.processPage.elementUrls["_N91RQUVEEeK93ZZqiMLBsA"] = ["Product Owner","process.openup.base/capabilitypatterns/product_owner_46EE4F32.html"];
contentPage.processPage.elementUrls["_N5e8wUVEEeK93ZZqiMLBsA"] = ["Analyst","process.openup.base/capabilitypatterns/analyst_6BC3A77A.html"];
contentPage.processPage.elementUrls["_N4bz4UVEEeK93ZZqiMLBsA"] = ["Developer Test","process.openup.base/capabilitypatterns/developer_test_3C043481.html"];
contentPage.processPage.elementUrls["_Bn6qoFQ0Ed2i9JHp7xurvw"] = ["Lifecycle Architecture Milestone","process.openup.base/deliveryprocesses/lifecycle_architecture_milestone_6645814A.html"];
contentPage.processPage.elementUrls["_DZttwZlXEeGlkdGl1HQlDA"] = ["Deployment Engineer","process.openup.base/capabilitypatterns/deployment_engineer_BB14036.html"];
contentPage.processPage.elementUrls["_DaTjqJlXEeGlkdGl1HQlDA"] = ["Release","process.openup.base/capabilitypatterns/release_C0F42C89.html"];
contentPage.processPage.elementUrls["_N9_CQUVEEeK93ZZqiMLBsA"] = ["Developer Test","process.openup.base/capabilitypatterns/developer_test_D90719F5.html"];
contentPage.processPage.elementUrls["_N4OYgUVEEeK93ZZqiMLBsA"] = ["Project Plan","process.openup.base/capabilitypatterns/project_plan_B11ABDC0.html"];
contentPage.processPage.elementUrls["_y7a0GJiLEeGOvpP1fVrVNA"] = ["Package the Release","process.openup.base/capabilitypatterns/package_the_release_FED024DC.html"];
contentPage.processPage.elementUrls["_CoJVUdOPEdyqlogshP8l4g"] = ["Ongoing Tasks","process.openup.base/capabilitypatterns/ongoing_tasks_BCA6545C.html"];
contentPage.processPage.elementUrls["_Dlo8wdo8EdyzZqGyZ7hwdw"] = ["Test Script","process.openup.base/capabilitypatterns/test_script_BE525A6E.html"];
contentPage.processPage.elementUrls["_dC4w4ZojEd2XAqcHTC2Siw"] = ["Test Log","process.openup.base/capabilitypatterns/test_log_2847C77A.html"];
contentPage.processPage.elementUrls["_pzQU0dONEdyqlogshP8l4g"] = ["Transition Phase Iteration","process.openup.base/capabilitypatterns/transition_phase_iteration_57B0A6B5.html"];
contentPage.processPage.elementUrls["_6R37MN_1EdyOsumnGvWsEg"] = ["[Technical Specification]","process.openup.base/capabilitypatterns/technical_specification_slot_799A6A77.html"];
contentPage.processPage.elementUrls["_qRAugZlXEeGlkdGl1HQlDA"] = ["Prepare for Release","process.openup.base/capabilitypatterns/prepare_for_release_ABB9ED05.html"];
contentPage.processPage.elementUrls["_HDOWUtOLEdyqlogshP8l4g"] = ["Test Case","process.openup.base/capabilitypatterns/test_case_36958574.html"];
contentPage.processPage.elementUrls["_N5jOMUVEEeK93ZZqiMLBsA"] = ["Tester","process.openup.base/capabilitypatterns/tester_2C4C8696.html"];
contentPage.processPage.elementUrls["_mqtdUFQzEd2i9JHp7xurvw"] = ["Lifecycle Objectives Milestone","process.openup.base/deliveryprocesses/lifecycle_objectives_milestone_CEAD6E5B.html"];
contentPage.processPage.elementUrls["_zjF0ANOJEdyqlogshP8l4g"] = ["Manage Iteration","process.openup.base/capabilitypatterns/manage_iteration_D96F88D6.html"];
